apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.databaseServiceName }}
  namespace: {{ .Values.namespace }} 
spec:
  selector:
    app: {{ .Values.databaseDeploymentName }}
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP  